### ISSUE TITLE
Pods are healthy, but operator says: minimum replication size is not met, only 0 are healthy

### ISSUE THREAD

**Issue by sim1** [amaizfinance/redis-operator#29]
Kubernetes 1.20.4
Redis-operator manifests:
```
kustomize build github.com/sim1/katalog/redis-operator/default?ref=0.0.4
```
(upstream kustomize remote + 0.2.0 -> latest image tag rewrite due to #24)

Manifest:
```
---
apiVersion: k8s.amaiz.com/v1alpha1
kind: Redis
metadata:
  # the .metadata.labels will be added to all generated resources along with the
  # redis=example label
  labels:
    component: redis
  # the name of the Redis resource will be used as a label for all generated resources,
  # and as the infix or suffix for them.
  name: super
spec:
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - redis
            topologyKey: kubernetes.io/hostname
          weight: 70
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default

  dataVolumeClaimTemplate:
    metadata:
      name: redis-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  # Redis container definition (required)
  # image, resources and securityContext are the same as found in v1.Container.
  # More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core
  redis:
    image: redis:alpine
    initialDelaySeconds: 10
    resources:
      requests:
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      readOnlyRootFilesystem: true
      runAsUser: 7777777
      runAsGroup: 7777777
      fsGroup: 7777777
      runAsNonRoot: true
```

Logs:
```
~ » k get svc,ep,pod
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/redis-super            ClusterIP   10.35.154.189   <none>        6379/TCP   118s
service/redis-super-headless   ClusterIP   None            <none>        6379/TCP   118s
service/redis-super-master     ClusterIP   10.44.178.120   <none>        6379/TCP   118s

NAME                             ENDPOINTS                                                    AGE
endpoints/redis-super            100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   118s
endpoints/redis-super-headless   100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   118s
endpoints/redis-super-master     <none>                                                       118s

NAME                         READY   STATUS                       RESTARTS   AGE
pod/redis-super-0            1/1     Running                      0          118s
pod/redis-super-1            1/1     Running                      0          82s
pod/redis-super-2            1/1     Running                      0          45s
pod/super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          118s
~ » k get svc,ep,pod
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/redis-super            ClusterIP   10.35.154.189   <none>        6379/TCP   119s
service/redis-super-headless   ClusterIP   None            <none>        6379/TCP   119s
service/redis-super-master     ClusterIP   10.44.178.120   <none>        6379/TCP   119s

NAME                             ENDPOINTS                                                    AGE
endpoints/redis-super            100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   119s
endpoints/redis-super-headless   100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   119s
endpoints/redis-super-master     <none>                                                       119s

NAME                         READY   STATUS                       RESTARTS   AGE
pod/redis-super-0            1/1     Running                      0          119s
pod/redis-super-1            1/1     Running                      0          83s
pod/redis-super-2            1/1     Running                      0          46s
pod/super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          119s
~ » kns redis-operator
stern Set context namespace to "redis-operator"
.
~ » stern .
+ redis-operator-6bd5b89477-74lp9 › redis-operator
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.120Z","logger":"cmd","msg":"Redis-Operator Version: latest"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.120Z","logger":"cmd","msg":"Go Version: go1.15.1"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"cmd","msg":"Version of operator-sdk: v0.17.1"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"leader","msg":"Trying to become the leader."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:56.728Z","logger":"leader","msg":"No pre-existing lock was found."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:56.773Z","logger":"leader","msg":"Became the leader."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:59.309Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:59.310Z","logger":"cmd","msg":"Registering Components."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.590Z","logger":"metrics","msg":"Metrics Service object created","Service.Name":"redis-operator-metrics","Service.Namespace":"redis-operator"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.590Z","logger":"cmd","msg":"Starting the Cmd."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.591Z","logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.591Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.692Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.995Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.095Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.196Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.298Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.401Z","logger":"controller-runtime.controller","msg":"Starting Controller","controller":"redis-controller"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.401Z","logger":"controller-runtime.controller","msg":"Starting workers","controller":"redis-controller","worker count":1}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.265Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.307Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.349Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.442Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.485Z","logger":"controller_redis","msg":"Applied *v1.ConfigMap","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.519Z","logger":"controller_redis","msg":"Applied *v1beta1.PodDisruptionBudget","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.651Z","logger":"controller_redis","msg":"Applied *v1.StatefulSet","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.856Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.859Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.972Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.999Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.001Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.029Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.030Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:53.534Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:38:31.895Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:38:36.898Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:12.902Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:22.904Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:32.907Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:50.139Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}


redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:40:05.142Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
^C
~ » k get pod -n super
NAME                     READY   STATUS                       RESTARTS   AGE
redis-super-0            1/1     Running                      0          2m48s
redis-super-1            1/1     Running                      0          2m12s
redis-super-2            1/1     Running                      0          95s
super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          2m48s
~ »
```
