### ISSUE TITLE
Operator gets stuck at syncing the statefull set when container resources are specified in a non "normal" form

### ISSUE THREAD

**Issue by stocksr** [amaizfinance/redis-operator#45]
With this in my crd 
```
 redis:
    image: redis:6.2.6-alpine
    initialDelaySeconds: 10
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 0.8Gi
```       

the stateful set gets created with 
```
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 858993459200m
```
and the operator keeps logging
`... "logger":"controller_redis","msg":"Applied *v1.StatefulSet","Namespace ...` 
every 2 seconds

if I change my definition to 

```
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 800Mi
```

the stateful set is created with identical values and the operator moves on to the next step.

P.S.  To help other people find this issue:  everything was "running" but there was no master label assigned to any of the pods, so I was unable to connect and the pod logs all showed the instances running as standalone servers, the ConfigMap did not have the replicaof line.

I guess something is normalising the resource values as the stateful set is created, but not normalising them before the diff check.
