### ISSUE TITLE
Persistent Volumes

### ISSUE THREAD

**Issue by pms1969** [amaizfinance/redis-operator#6]
Do you have a good example of how to add Persistent Volumes to a cluster?  I've noticed that there is some data volume template in the definition, but don't really know how to configure it.

Cheers,

**Comment by pms1969** [comment]
I've added 
```yaml
  dataVolumeClaimTemplate:
  - 
    metadata:
      name: test-redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```

But just get back 
```log
spec.dataVolumeClaimTemplate in body must be of type object: "array"
```
which has me a bit confused.  Any ideas?
